"""empty message

Revision ID: 534697f4824a
Revises: b1f9d1369c80
Create Date: 2020-02-12 23:58:20.477894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534697f4824a'
down_revision = 'b1f9d1369c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user2_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'user2_id')
    # ### end Alembic commands ###
