"""empty message

Revision ID: 77635da06f44
Revises: 534697f4824a
Create Date: 2020-02-17 09:44:41.888272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77635da06f44'
down_revision = '534697f4824a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('video_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_views_timestamp'), 'video_views', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('bio', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('complete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('firstName', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('studyField', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('university', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_firstName'), 'user', ['firstName'], unique=False)
    op.create_index(op.f('ix_user_lastName'), 'user', ['lastName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lastName'), table_name='user')
    op.drop_index(op.f('ix_user_firstName'), table_name='user')
    op.drop_column('user', 'university')
    op.drop_column('user', 'studyField')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_column('user', 'complete')
    op.drop_column('user', 'bio')
    op.drop_index(op.f('ix_video_views_timestamp'), table_name='video_views')
    op.drop_table('video_views')
    op.drop_table('video_rates')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
