"""empty message

Revision ID: 89c92ab2df1b
Revises: 77635da06f44
Create Date: 2020-02-18 23:33:30.310336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c92ab2df1b'
down_revision = '77635da06f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('video_link', sa.String(length=400), nullable=True),
    sa.Column('video_link_id', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_video_timestamp'), 'course_video', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_video_timestamp'), table_name='course_video')
    op.drop_table('course_video')
    # ### end Alembic commands ###
