"""empty message

Revision ID: d3f4d120aa13
Revises: 98325aa4f9b8
Create Date: 2020-02-03 11:54:11.285474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f4d120aa13'
down_revision = '98325aa4f9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('img_url', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_timestamp'), 'course', ['timestamp'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_timestamp'), 'enrollment', ['timestamp'], unique=False)
    op.add_column('post', sa.Column('send_receive', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_post_send_receive'), 'post', ['send_receive'], unique=False)
    op.add_column('user', sa.Column('friends', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('img_url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_url')
    op.drop_column('user', 'friends')
    op.drop_index(op.f('ix_post_send_receive'), table_name='post')
    op.drop_column('post', 'send_receive')
    op.drop_index(op.f('ix_enrollment_timestamp'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_course_timestamp'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
